packages:
  - playground
  - docs
  - packages/*
  - examples/*

patchedDependencies:
  iso-ucan: patches/iso-ucan.patch

catalogs:
  dev:
    '@antfu/eslint-config': ^6.2.0
    '@antfu/ni': ^28.0.0
    '@unocss/reset': ^66.5.10-beta.1
    ansis: ^4.2.0
    bumpp: ^10.3.2
    chokidar: ^5.0.0
    eslint: ^9.39.1
    exsolve: ^1.0.8
    lightningcss: ^1.30.2
    lint-staged: ^16.2.7
    magic-string: ^0.30.21
    simple-git-hooks: ^2.13.1
    tinyglobby: 0.2.15
    tsdown: ^0.17.0-beta.5
    tsx: ^4.21.0
    typescript: ^5.9.3
    unocss: ^66.5.10-beta.1
    unplugin-vue: ^7.0.8
    vite: ^7.2.6
  prod:
    cborg: ^4.3.1
    iso-base: ^4.2.1
    iso-did: ^2.1.1
    iso-signatures: ^0.5.1
    iso-ucan: ^0.4.2
    pako: ^2.1.0
    vue: ^3.5.25
  testing:
    vitest: ^4.0.14
    vitest-package-exports: ^0.1.1
    yaml: ^2.8.2
  types:
    '@types/node': ^24.10.1
    '@types/pako': ^2.0.4
  utils:
    tinyexec: ^1.0.2

ignoreWorkspaceRootCheck: true

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks

shellEmulator: true
