catalogMode: prefer

cleanupUnusedCatalogs: true

ignoreWorkspaceRootCheck: true

shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - ts-api-utils@2.3.0
packages:
  - playground
  - docs
  - packages/*
  - examples/*
patchedDependencies:
  iso-ucan: patches/iso-ucan.patch

catalogs:
  dev:
    '@antfu/eslint-config': ^7.2.0
    '@antfu/ni': ^28.2.0
    '@unocss/reset': ^66.6.0
    ansis: ^4.2.0
    bumpp: ^10.4.0
    chokidar: ^5.0.0
    eslint: ^9.39.2
    exsolve: ^1.0.8
    lightningcss: ^1.31.1
    lint-staged: ^16.2.7
    magic-string: ^0.30.21
    rollup-plugin-visualizer: 6.0.5
    simple-git-hooks: ^2.13.1
    tinyglobby: 0.2.15
    tsdown: ^0.20.1
    tsx: ^4.21.0
    typescript: ^5.9.3
    unocss: ^66.6.0
    unplugin-vue: ^7.1.1
    vite: ^7.3.1
  prod:
    '@ipld/dag-json': ^10.2.6
    cborg: ^4.5.8
    date-fns: ^4.1.0
    iso-base: ^4.3.0
    iso-did: ^2.1.1
    iso-signatures: ^0.5.1
    iso-ucan: ^0.4.2
    multiformats: ^13.4.2
    pako: ^2.1.0
    vue: ^3.5.27
  testing:
    vitest: ^4.0.18
    vitest-package-exports: ^1.1.2
    yaml: ^2.8.2
  types:
    '@types/node': ^25.2.0
    '@types/pako': ^2.0.4
  utils:
    tinyexec: ^1.0.2
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
